### ISSUE TITLE
🐛 Install command failed

### ISSUE THREAD

**Issue by kaermorchen** [flex-development/docast-parse#11]
### Prerequisites

- [X] read documentation
- [X] searched open issues for existing bug report
- [X] searched closed issues for solution(s) or feedback

### Current behavior

```
npm i @flex-development/docast-parse@flex-development/docast-parse
npm ERR! code 1
npm ERR! command failed
npm ERR! command sh -c chmod +x .husky/* && husky install
npm ERR! chmod: cannot access '.husky/*': No such file or directory
```

### Reproduction

```
npm i @flex-development/docast-parse@flex-development/docast-parse
```

### Expected behavior

It should be installed

### Package version

-

### Node.js version

v18.12.1

### Package manager version

9.2.0

### Operating system (environment)

linux

### Additional context

Hello.

I want to try your package, but the install command throw the error.

**Comment by unicornware** [comment]
@kaermorchen thanks for your interest in this project and for catching this bug! i use `husky` in all of my projects, so i forgot to check the `postinstall` command 😅

can you install [`75f8e9f904e2c1d0a0edce27f8e5b42f7712ace2`][1] to check if this has been resolved?

```zsh
npm i @flex-development/docast-parse@flex-development/docast-parse#75f8e9f904e2c1d0a0edce27f8e5b42f7712ace2
```

(correct me if i'm wrong about the exact syntax of the install command. i checked the docs, but i haven't been hands-on with `npm` for a while now)

[1]: https://github.com/flex-development/docast-parse/commit/75f8e9f904e2c1d0a0edce27f8e5b42f7712ace2

**Comment by kaermorchen** [comment]
@unicornware The install command works! Thanks for the fast fix.
